version: 0.2
phases: 
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands: 
      - echo Tests running
      - mvn test
  build: 
    commands: 
      - echo Tests completed
      - echo Build running
      - mvn package  
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
